/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* CART */
export const CHANGE_COUNT = "CHANGE_COUNT";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

/* SELLER */
export const LOGIN_SELLER = "LOGIN_SELLER";
export const LOGIN_SELLER_SUCCESS = "LOGIN_SELLER_SUCCESS";
export const LOGIN_SELLER_ERROR = "LOGIN_SELLER_ERROR";
export const REGISTER_SELLER = "REGISTER_SELLER";
export const REGISTER_SELLER_SUCCESS = "REGISTER_SELLER_SUCCESS";
export const REGISTER_SELLER_ERROR = "REGISTER_SELLER_ERROR";
export const LOGOUT_SELLER = "LOGOUT_SELLER";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/** ALERT */
export const TOGGLE_ALERT = "SURVEY_SAVE";

export * from "./auth/actions";
